# Generated by Django 5.1.6 on 2026-03-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=150)),
                ("mobile", models.CharField(max_length=15)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("dob", models.DateField()),
                ("college", models.CharField(max_length=200)),
                ("about", models.TextField(blank=True, max_length=500)),
                (
                    "skills",
                    models.CharField(
                        help_text="Comma-separated skills", max_length=500
                    ),
                ),
                ("intro_video_url", models.URLField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
