# Generated by Django 5.1.6 on 2026-03-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_is_banned"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("EMPLOYER", "Employer"),
                            ("STUDENT", "Student"),
                        ],
                        default="STUDENT",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
