# Generated by Django 5.1.6 on 2026-03-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_application_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='earnings',
            field=models.CharField(default='', help_text='e.g. ₹500 or $10/hr', max_length=50),
        ),
        migrations.AddField(
            model_name='gig',
            name='timing',
            field=models.CharField(default='', help_text='e.g. 10 AM to 2 PM', max_length=100),
        ),
    ]
