# Generated by Django 5.1.6 on 2026-03-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_gig_earnings_gig_timing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gig",
            name="timing",
        ),
        migrations.AddField(
            model_name="gig",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gig",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
