# Generated by Django 5.1.6 on 2026-03-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_gig_timing_gig_date_gig_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="profile_picture_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
