# Generated by Django 5.1.6 on 2026-03-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_employerprofile_profile_picture_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_email", models.EmailField(max_length=254)),
                ("action", models.CharField(max_length=50)),
                ("target", models.CharField(max_length=200)),
                ("details", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
