# Generated by Django 5.1.6 on 2026-03-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_adminlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gig",
            name="image_url",
        ),
        migrations.AddField(
            model_name="gig",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="gigs/"),
        ),
    ]
