# Generated by Django 5.1.6 on 2026-03-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userrole_is_frozen"),
        ("core", "0012_remove_gig_image_url_gig_image"),
    ]

    operations = []
