# Generated by Django 5.1.6 on 2026-03-19 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_merge_20260318_2013"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_user_id", models.BigIntegerField(unique=True)),
                ("telegram_chat_id", models.BigIntegerField()),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "telegram_first_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "telegram_last_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_registration",
                        to="core.userprofile",
                    ),
                ),
            ],
        ),
    ]
