# Generated by Django 5.1.6 on 2026-03-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_telegramregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="registration_platform",
            field=models.CharField(
                choices=[("web", "Web"), ("telegram", "Telegram"), ("both", "Both")],
                default="web",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TelegramEmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("telegram_user_id", models.BigIntegerField()),
                ("otp_code", models.CharField(max_length=6)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email", "telegram_user_id"],
                        name="core_telegr_email_f92db4_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="core_telegr_expires_912748_idx"
                    ),
                ],
            },
        ),
    ]
