# Generated by Django 5.1.6 on 2026-03-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_userprofile_registration_platform_telegramemailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="suitability_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
