# Generated by Django 5.1.6 on 2026-03-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_application_suitability_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="tg_persistence", max_length=255, unique=True
                    ),
                ),
                ("user_data", models.JSONField(default=dict)),
                ("chat_data", models.JSONField(default=dict)),
                ("bot_data", models.JSONField(default=dict)),
                ("conversations", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
