# Generated by Django 5.1.6 on 2026-03-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_application_status_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gig",
            name="time",
        ),
        migrations.AddField(
            model_name="gig",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gig",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gig",
            name="earnings",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
