# Generated by Django 5.1.6 on 2026-03-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_gig_time_gig_end_time_gig_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
